### ISSUE TITLE
FTPSB-001: Wrong TPS reported when sprinting.

### ISSUE THREAD

**Issue by spooky-dude3** [Pyrix25633/Fabric-FabricTPS#2]
**Describe the bug**
When the game is sprinting /fabric tps reports the tps as 20 when its actually much higher.

**To Reproduce**
Run the command /tick sprint [time], with [time] being how long you want it to sprint i.e. 20s
when the game is sprinting run /fabric tps.

**Expected behavior**
the reported tps should be the same or near the value that the server reports when the tick sprint is finishes.

**Screenshots**
running the command in single player world
![image](https://github.com/user-attachments/assets/85433838-fb6a-40d2-a699-fd1fc8dad5ed)

running the command on multiplayer server
![temp](https://github.com/user-attachments/assets/c42d76df-cd76-4359-9d21-f16ca8dbb5f9)

**Comment by Pyrix25633** [comment]
Hello, yeah It's caused by my wrong supposition that the max tps is 20 [see here](https://github.com/Pyrix25633/Fabric-FabricTPS/blob/b844a7ad566d30d1c8887a5d783cd011f549acaa/src/main/java/net/rupyber_studios/fabric_tps/command/FabricTPSCommand.java#L39).
Can you tell me since when the tick sprint command exists?
Since I'm currently on an unplanned stay at the hospital 😢 I do not have access to my computer, but I'll look at it as soon as possible, I thin I could solve it by actually counting the ticks per second instead of using the mspt to calculate it assuming the max is 20. Please let me know, I really didn't think of this, great eye!

**Comment by spooky-dude3** [comment]
I only heard of it a few weeks ago.  Apparently /tick was added in 1.20.3 according to [the wiki](https://minecraft.wiki/w/Commands/tick), and aside from sprint it looks like there are other functions such as changing the target tick rate, freezing ticking, and /tick query which displays mspt info and the target tick rate.  

Since this mod calculates the tick rate based on mspt, when the tick rate is below 20 but mspt is less than 50 the mod still reports 20tps.
![image](https://github.com/user-attachments/assets/32a0d913-9be1-4711-8bf8-d7976c3cdaa4)

Afaik the only time the tick rate can be below 20 with a mspt less than 50 or sustained above 20, is when using the /tick command.  Because this is a somewhat niche command and those using it are likely aware of what its doing to their tps, and since the /tick query command can be used to asses the tick rate under these circumstances, I don't think updating this mod for these edge cases would be too important.

**Comment by Pyrix25633** [comment]
Well, while you are right, I'll still fix this for 1.20.6 and 1.21.1 versions just to keep my brain busy with something as simple as this.

**Comment by Pyrix25633** [comment]
Fixed for 1.20.6 with 1.4.3a, will release 1.5.0 for 1.21.1 soon!
It was an easy fix, instead of calculating it using the tick duration, now it is calculated using the time difference between the start of ticks (tickDelta).
tickTime = time between tick start and tick end
tickDelta = time between previous tick start and current tick start
So the > 20 is no longer necessary.
